name: Rust Setup
description: Rust Setup
runs:
  using: "composite"
  steps:
    - name: Rustup
      shell: bash
      run: |
          set -e
          rustup set profile minimal
          rustup install stable
    - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
