[package]
name = "semv"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
semver = "1.0.26"
serde = { version = "1.0.223", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
assert_cmd = "2.0.17"
predicates = "3.0.3"